### ISSUE TITLE
Выполнение async-функции из примера

### ISSUE THREAD

**Issue by chercgpb** [amironov73/PythonIrbis#24]
не удалось запустить асинхронный код из примера - 

```
irbis.init_async()
irbis.irbis_event_loop.run_until_complete(do_async_stuff())
irbis.close_async()
```

Вот такое исправление сработало
```
    event_loop = asyncio.get_event_loop()
    tasks = [event_loop.create_task(do_async_stuff())]
    wait_tasks = asyncio.wait(tasks)
    event_loop.run_until_complete(wait_tasks)
    event_loop.close()
```

**Comment by nrot** [comment]
Этот вопрос не относиться к PythonIrbis, поскольку ```irbis.irbis_event_loop``` объект библиотеки asyncio и PythonIrbis лишь делает несколько тонких прослоек для его использования, в частности метод ```run_until_complete``` является прямым вызовом из библиотеки asyncio. 
Так как код функции ```do_async_stuff``` не показан я могу предположить что вы определили её как синхронную функцию (обычную). Дальше в примере видно, что вызов асинхронной функции работает, в то время как синхронная вызывает ошибку.
Код примера
```python
import asyncio
import time 

async def async_function():
    print("start async")
    await asyncio.sleep(3)
    print("end async")

def sync_function():
    print("start sync")
    time.sleep(3)
    print("end sync")

event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(async_function())
event_loop.run_until_complete(sync_function())
event_loop.close()
```
Вывод:
```
DeprecationWarning: There is no current event loop
  event_loop = asyncio.get_event_loop()
start async
end async
start sync
end sync
Traceback (most recent call last):
test.py, line 16, in <module>
event_loop.run_until_complete(sync_function())
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

**Comment by chercgpb** [comment]
Вот, кажется, эта прослойка не срабатывает

```
import irbis

from env import JOURN

TEST_MFN = 1283 # Алешкин Наша молодежь
SUMMARY_DESCRIPTION_FILENAME = "Asp_H.pft" # файл формата сводного описания

def main():
    async def do_async_stuff():
        global TEST_MFN, SUMMARY_DESCRIPTION_FILENAME 

        result = await connection.connect_async()
        if not result:
            print('Failed to connect')
            return

        print('Connected')

        summary = await connection.read_text_file_async(f"2.Deposit.{SUMMARY_DESCRIPTION_FILENAME}")
        print(summary)

        await connection.disconnect_async()
        print('Disconnected')


    # =============================================

    connection = irbis.Connection()
    connection.parse_connection_string(
        f"host={JOURN.get('host')};port={JOURN.get('port')};username={JOURN.get('username')};password={JOURN.get('password')};db={JOURN.get('database')}")

    irbis.init_async()
    irbis.irbis_event_loop.run_until_complete(do_async_stuff())
    irbis.irbis_event_loop.close()


if __name__ == '__main__':
    main()
```

python 3.79


```
Traceback (most recent call last):
  File "C:\Users\cher\PycharmProjects\journ-bot\main_async.py", line 39, in <module>
    main()
  File "C:\Users\cher\PycharmProjects\journ-bot\main_async.py", line 34, in main
    irbis.irbis_event_loop.run_until_complete(do_async_stuff())
AttributeError: 'NoneType' object has no attribute 'run_until_complete'

Process finished with exit code 1
```

**Comment by nrot** [comment]
Вы правы глобальный объект irbis_event_loop получает значение только в момент подключения библиотеки irbis - в этот момент переменная имеет значение None. И после вызова ```init_async()``` значение в главном модуле не изменяется. Я внесу патч с исправлением, после проверок это попадет в основную ветку.
