### ISSUE TITLE
ломается .readRecords

### ISSUE THREAD

**Issue by chercgpb** [amironov73/PythonIrbis#26]
в некоторых ситуациях, в зависимости от БД, такой код выдаёт ошибку 

```
connection = irbis.Connection()
connection.parse_connection_string("host=localhost;port=6666;username=test;password=test")
connection.connect()
search_params = irbis.SearchParameters()
search_params.database = 'PERI'
search_params.sequential = f"if v11<>'' then '1' else '0' fi"
found = connection.search(search_params)
records = connection.read_record(*found)
```

```
Traceback (most recent call last):
  File "C:\Users\cher\AppData\Local\Programs\Python\Python37-32\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 10, in <module>
  File "C:\Users\cher\PycharmProjects\journ-bot\venv-python37\lib\site-packages\irbis\connection.py", line 1219, in read_records
    record.parse(parts)
  File "C:\Users\cher\PycharmProjects\journ-bot\venv-python37\lib\site-packages\irbis\records\abstract.py", line 121, in parse
```

**Comment by chercgpb** [comment]
Ошибку не получаю, если указываю БД таким образом

```
connection.database = 'PERI'
```
